<?php

// I hate notice errors
ini_set('error_reporting', ini_get('error_reporting') & ~E_NOTICE);

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'sirius_btu') . '/sirius_btu.menu.inc';
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'sirius_btu') . '/sirius_btu.permission.inc';
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'sirius_btu') . '/sirius_btu.csg.inc';

/**
 * Implements hook_sirius_domain_component_info
 */

function sirius_btu_sirius_domain_component_info() {
  return array(
    'btu:csg' => array(
      'title' => 'BTU - Class Size Grievances',
      'description' => 'Custom functionality for the Boston Teachers\' Union.',
    ),
  );
}

/**
 * Implements hook_sirius_config_links_alter()
 */

function sirius_btu_sirius_config_links_alter(&$links) {
  $links['btu']['title'] = 'BTU';
  $links['btu']['links']['sirius/btu/csg'] = array('title' => 'Class Size Grievances', 'description' => 'Manage Class Size Grievances');
}

/**
 * Implements hook_sirius_cron_scan_info()
 */

function sirius_btu_sirius_cron_scan_info() {
  $items['btu_csg_notify'] = array(
    'title' => 'BTU Class Size Grievances Notification Email',
    'description' => 'Send an email notification with the latest class size grievances',
    'schedule' => 'daily',
    'callback' => 'sirius_btu_csg_notify_scan',
    'multidomain' => TRUE,
    'component' => 'btu:csg',
  );

  return $items;
}

/**
 * Implements hook_sirius_flood_info
 */

function sirius_btu_sirius_flood_info() {
  $info['sirius_btu_csg_submit'] = array(
    'title' => 'BTU: Class Size Grievances: New Submissions',
    'threshold_default' => 15,
    'window_default' => 5*60,
    'description' => 'A user attempted to submit a class size grievance',
  );

  return $info;
}

/**
 * Implements hook_sirius_backlinks_from_node_alter
 */

function sirius_btu_sirius_backlinks_from_node_alter(&$links, $node) {
  if ($node->type == 'sirius_log' && $node->field_sirius_category['und'][0]['value'] == 'btu:csg') {
    $links['sirius/btu/csg'] = array('name' => 'All Class Size Grievances');
  }
}

/**
 * Implements hook_sirius_access_info
 */

function sirius_btu_sirius_access_info() {
  $infos = array();
  Sirius_Btu_Csg_Access::getInstance()->setInfo($infos);
  return $infos;
}

/**
 * Implements hook_form_alter
 * 
 * Change the login prompt from "username"
 */

function sirius_btu_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    $form['name']['#title'] = t('Username (BPS ID)');
    $form['name']['#description'] = '';
  }
}

/**
 * Implements hook_node_view_alter
 */

function sirius_btu_node_view($node, $view_mode, $langcode) {
  // BTU wants to hide SSN and AAT
  if ($view_mode == 'full' && $node->type == 'sirius_worker') {
    unset($node->content['field_sirius_ssn']);
    unset($node->content['field_sirius_aat']);
  }
}
