<?php

// I hate notice errors
ini_set('error_reporting', ini_get('error_reporting') & ~E_NOTICE & ~E_DEPRECATED);

require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.menu.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.permission.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.epayperiod.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.payperiod.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.cache.inc';

require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_payperiod_entries.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_payperiod_entries_view.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_payperiod_entries_summary.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_payperiod_entries_edit.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_payperiod_entries_reconcile.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_worker_hours.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_employer_hours.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.page_config.inc';

require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_hour/sirius_hour.report_by_ms.inc';


/**
 * Implements hook_sirius_jsonfield_form_definitions 
 */

/*
function sirius_hour_sirius_jsonfield_form_definitions() {
  $definitions['node']['sirius_payperiod']['field_sirius_json'] = sirius_hour_payperiod_definition();
  return $definitions;
}
*/

/**
 * Implements hook_node_insert()
 */

function sirius_hour_node_insert($node) {
	if ($node->type == 'sirius_payperiod') { sirius_hour_cache_set($node); }
}

/**
 * Implements hook_node_update()
 */

function sirius_hour_node_update($node) {
	if ($node->type == 'sirius_payperiod') { sirius_hour_cache_set($node); }
}

/**
 * Implements hook_node_delete()
 */

function sirius_hour_node_delete($node) {
	if ($node->type == 'sirius_payperiod') { sirius_hour_cache_clear($node); }
}

/**
 * Implements hook_node_presave()
 */

function sirius_hour_node_presave($node) {
	if ($node->type == 'sirius_payperiod') { sirius_hour_payperiod_set_title($node); }
}

function sirius_hour_payperiod_set_title($node) {
	$title = "Payperiod: "; 

	$worker_nid = $node->field_sirius_worker['und'][0]['target_id'];
	if ($worker_nid) { $title .= substr(sirius_node_title($worker_nid), 0, 55); } else { $title .= '[no employer]'; }

	$title .= ' / '; 

	$employer_nid = $node->field_grievance_shop['und'][0]['target_id'];
	if ($employer_nid) { $title .= substr(sirius_node_title($employer_nid), 0, 55); } else { $title .= '[no worker]'; }

	$title .= ' / ';
	if ($node->field_sirius_datetime['und']) { $title .= sirius_date_date($node, 'field_sirius_datetime', $format = 'Y-m-d'); } else { $title .= '[no date]'; }

	$node->title = $title;
}

/***
 * Implements hook_report_cache_info() 
 */

/*
function sirius_hour_report_cache_info() {
  $items = array();
  $items += sirius_hour_report_by_ms_info();
  return $items;
}
*/

/**
 * Implements hook_sirius_domain_component_info
 */

function sirius_hour_sirius_domain_component_info() {
  return array(
    'hour:reconcile' => array(
      'title' => 'Hour - Reconcile',
      'description' => 'Allow multiple sources for hours, and reconcile which is "live".',
    ),
    'hour:transmittal' => array(
      'title' => 'Hour - Transmittal Sheets',
      'description' => 'Support for "Transmittal Sheets", paper-based tools for employers to report hours.',
    ),
  );
}


/**
 * Implements hook_sirius_config_links_alter()
 */

function sirius_hour_sirius_config_links_alter(&$links) {
  if (!isset($links['hours'])) {
    $links['hour'] = array('title' => 'Hours');
  }
  $links['hour']['links']['sirius/hour/config'] = array('title' => 'Hour settings', 'description' => 'General settings for hour tracking.');
  $links['hour']['links']['sirius/hour/search/month'] = array('title' => 'Month Search', 'description' => 'Raw hour search (by month)');
}
