<?php

// I hate notice errors
ini_set('error_reporting', ini_get('error_reporting') & ~E_NOTICE & ~E_DEPRECATED);

require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_teamsters631/sirius_teamsters631.menu.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_teamsters631/sirius_teamsters631.ebnotify.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_teamsters631/sirius_teamsters631.permission.inc';
require_once DRUPAL_ROOT . '/sites/all/modules/_custom/sirius_teamsters631/sirius_teamsters631.badge.inc';

/**
 * Implements hook_taxonomy_term_update() 
 */

function sirius_teamsters631_taxonomy_term_update($term) {
  $vid = $term->vid;
  $vocabulary = taxonomy_vocabulary_load($vid);
  if ($vocabulary->machine_name == 'sirius_member_status') { sirius_teamsters631_taxonomy_term_update_ebnotify($term); }
}
 

function sirius_teamsters631_oneoff_notification_update() {
	// Get the last job created by this job at this employer with this type.
	$sql = "select entity_id from field_data_field_sirius_dispatch_medium ";
	$sql .= "where entity_type = 'node' ";
	$sql .= "and bundle = 'sirius_worker' ";
	$sql .= "and delta = 2 "; 
	$sql .= "and field_sirius_dispatch_medium_value = 'email' ";
	$sql .= "order by entity_id ";

	$worker_nids = array();
	$stmt = db_query($sql, array());
	while ($hr = $stmt->fetchAssoc()) {
		$worker_nids[] = $hr['entity_id'];
	}

	foreach ($worker_nids as $worker_nid) {
		print "Scanning: $worker_nid\n";
		$sql = "select * from field_data_field_sirius_type, field_data_field_sirius_category, field_data_field_sirius_log_handler ";
		$sql .= "where field_data_field_sirius_type.entity_type = 'node' and field_data_field_sirius_type.bundle = 'sirius_log' ";
		$sql .= "and field_data_field_sirius_category.entity_type = 'node' and field_data_field_sirius_category.bundle = 'sirius_log' ";
		$sql .= "and field_data_field_sirius_log_handler.entity_type = 'node' and field_data_field_sirius_log_handler.bundle = 'sirius_log' ";
		$sql .= "and field_data_field_sirius_type.entity_id = field_data_field_sirius_category.entity_id ";
		$sql .= "and field_data_field_sirius_category.entity_id = field_data_field_sirius_log_handler.entity_id ";
		$sql .= "and field_sirius_log_handler_target_id = :worker_nid ";
		$sql .= "and field_sirius_category_value = 'worker:dispatch' ";
		$sql .= "and field_sirius_type_value = 'update_preferences' ";
		$sql .= "limit 1 ";
		$stmt = db_query($sql, array(':worker_nid' => $worker_nid));
		$hr = $stmt->fetchAssoc();
		if ($hr) {
			print "... Already set preferences; skipping\n";
			continue; 
		}

		$sql = "select * from field_data_field_sirius_phone ";
		$sql .= "where entity_type = 'node' ";
		$sql .= "and entity_id = :worker_nid ";
		$stmt = db_query($sql, array(':worker_nid' => $worker_nid));
		$hr = $stmt->fetchAssoc();
		if (!$hr) {
			print "... No phone; skipping.\n";
			continue; 
		}

		$tables = array('field_data_field_sirius_dispatch_medium', 'field_revision_field_sirius_dispatch_medium');
		foreach ($tables as $table) {
			$sql = "update $table set field_sirius_dispatch_medium_value = 'sms' where entity_type = 'node' and entity_id = :worker_nid and delta = 2 ";
			$stmt = db_query($sql, array(':worker_nid' => $worker_nid));
		}
		print "... Updated.\n";
	}
}

function sirius_teamsters631_oneoff_10hrosha() {
	$sql = "select * from field_data_field_sirius_skill, field_data_field_sirius_skill_expire ";
	$sql .= "where field_data_field_sirius_skill.entity_type = 'node' ";
	$sql .= "and field_data_field_sirius_skill.bundle = 'sirius_worker' ";
	$sql .= "and field_data_field_sirius_skill_expire.entity_type = 'node' ";
	$sql .= "and field_data_field_sirius_skill_expire.bundle = 'sirius_worker' ";
	$sql .= "and field_data_field_sirius_skill_expire.entity_id = field_data_field_sirius_skill.entity_id ";
	$sql .= "and field_data_field_sirius_skill_expire.delta = field_data_field_sirius_skill.delta ";
	$sql .= "and field_sirius_skill_tid = 594 ";
	$sql .= "order by field_sirius_skill_expire_value ";

	$stmt = db_query($sql, array());
	while ($hr = $stmt->fetchAssoc()) {
		$worker_nid = $hr['entity_id'];
		$workers[$worker_nid] = array('delta' => $hr['delta'], 'expires' => $hr['field_sirius_skill_expire_value']);

		print "$worker_nid: $hr[field_sirius_skill_expire_value]\n";
	}
	print_r($workers);

	return;
	foreach ($worker_nids as $worker_nid) {
		$worker_node = node_load($worker_nid);
		// Grant 745, expire 5 years after [something]
		// Set 594 to expire [never]
	}
	print_r($worker_nids);
}
