<?php

function unite_casino_fields() {
	return array(
		'field_csno_type',
		'field_csno_slots_count',
		'field_csno_slots_date',
		'field_csno_tables_count',
		'field_csno_tables_date',
		'field_csno_book',
		'field_csno_book_txt',
		'field_csno_horse',
		'field_csno_online',
		'field_csno_online_txt',
		'field_csno_igame',
		'field_csno_igame_txt',
		'field_csno_txt1',
		'field_csno_txt2',
		'field_csno_txt3',
		'field_csno_txt4',
		'field_csno_regulator',
		'field_csno_source',
	);
}
